version: "3"

volumes:
  movie_drf:

services:
  postgres:
    image: postgres:14.3-alpine
    container_name: "movie_drf_postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "django_movie"
    volumes:
      - movie_drf:/var/lib/postgresql/data
